### PR TITLE
Job priority ajax

### LINKED ISSUE #45: Up-Downvote for priority reordering JS is broken

### PR DESCRIPTION
**Pull request by stianste**
FIxes #45

### CODE REVIEW

File: app/assets/javascripts/job_applications/job_applications.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+      else {
+        var priCur = parseInt(row.find(".priority").text());
+        var priNext = parseInt(row.next().find(".priority").text());
+        if (isNaN(priNext)) { priNext = parseInt(priCur) }
+        row.find(".priority").text(priNext);
+        row.next().find(".priority").text(priCur);
+        row.next().after(row);
+      }
+    });
+  });
```
Comment (aleksanb) [inline app/assets/javascripts/job_applications/job_applications.js:21]: You should factor out the Javascript that's common for after the if-else section.

File: app/assets/javascripts/job_applications/job_applications.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
+$(function() {
+  $(".up, .down").click(function (event) {
+    var $this = $(this);
+    event.preventDefault();
+    $.post(event.currentTarget.action).success(function () {
+      var row = $this.parents("tr");
+
+      if ($this.hasClass("up")) {
+        var priPrev = parseInt(row.prev().find(".priority").text());
+        if (isNaN(priPrev)) { priPrev = 1 }
```
Comment (aleksanb) [inline app/assets/javascripts/job_applications/job_applications.js]: In what cases can the priority be Nan?

**Comment by aleksanb** [comment]
You should squash your commits after you're finished.
