### PR TITLE
Fix interview table sorting

### LINKED ISSUE #569: Sorting applicants fails for several attributes
For example, we cannot sort applicants based on flag status ("Vil ha", "Vil ikke ha", et cetera), or if the applicants wants offer for other jobs. There is probably some  Javascript that must be updated to enable this behavior. Take a look in the `app/assets/javascript/old_samfundet/interviews.js` file.

### PR DESCRIPTION
**Pull request by eirikvaa**
* Upgrade jquery-tablesorter to sort text areas correctly
* Add jquery-tablesorter parser to parse select boxes
* Add class to other positions select box to sort these

Fixes #569

### CODE REVIEW

File: app/assets/javascripts/old_samfundet/interviews.js [hunk 1]
```diff
@@ -15,9 +15,22 @@ $(function () {
       type: 'text'
   });
 
+  $.tablesorter.addParser({
```
Comment (tollefj) [inline app/assets/javascripts/old_samfundet/interviews.js:18]: Given that we're still modifying this file, should we just move it outside to `javascripts/applicants/interviews.js`?

**Review by tollefj — APPROVED** [review]
Looks good. Other than if we should consider moving out "old_samfundet" javascript files to more appropriate locations if we still intend to modify them

File: app/assets/javascripts/old_samfundet/interviews.js (hunk 1 above)
Comment (eirikvaa) [reply app/assets/javascripts/old_samfundet/interviews.js:18]: Yeah, makes sense.
